:druby_uri: druby://127.0.0.1:5223
:interfaces:
  - ppp0
  - ppp1
  - ppp2
  - ppp3
  - ppp4
  - ppp5
  - dsl0
  - dsl1
  - dsl2
  - dsl3
  - dsl4
  - dsl5
:watchers:
  - watcher1@example.com
  - watcher2@example.com
:hours:
  - 08:00-20:00
